<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XIPL9722" ignored="0" name="Sprint1" tests="8" failures="2" timestamp="2021-06-30T09:36:37 IST" time="0.078" errors="0">
  <testcase name="test1" time="0.014" classname="retryAnalyzer.TestClass">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="retryAnalyzer.TestClass">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="retryAnalyzer.TestClass">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="retryAnalyzer.TestClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryAnalyzer.TestClass.test1(TestClass.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="retryAnalyzer.TestClass">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="retryAnalyzer.TestClass">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="retryAnalyzer.TestClass">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="retryAnalyzer.TestClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryAnalyzer.TestClass.test2(TestClass.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Sprint1 -->
